import type { Star } from '../types'

// Star data for constellation - positions in percentages relative to circle
export const starData: Star[] = [
  // Main chapter stars with Roman numerals
  { x: 50, y: 15, size: 'large', roman: 'I' },
  { x: 75, y: 20, size: 'medium', roman: 'II' },
  { x: 88, y: 35, size: 'small', roman: 'III' },
  { x: 92, y: 55, size: 'medium', roman: 'IV' },
  { x: 88, y: 75, size: 'large', roman: 'V' },
  { x: 75, y: 88, size: 'small', roman: 'VI' },
  { x: 55, y: 92, size: 'medium', roman: 'VII' },
  { x: 35, y: 88, size: 'large', roman: 'VIII' },
  { x: 20, y: 75, size: 'small', roman: 'IX' },
  { x: 12, y: 55, size: 'medium', roman: 'X' },
  { x: 18, y: 35, size: 'large', roman: 'XI' },
  { x: 28, y: 20, size: 'small', roman: 'XII' },
  { x: 65, y: 12, size: 'medium', roman: 'XIII' },
  { x: 82, y: 25, size: 'small', roman: 'XIV' },
  { x: 90, y: 45, size: 'medium', roman: 'XV' },
  { x: 85, y: 65, size: 'small', roman: 'XVI' },
  { x: 25, y: 35, size: 'medium', roman: 'XVII' },
  { x: 15, y: 45, size: 'small', roman: 'XVIII' },
  { x: 40, y: 18, size: 'medium', roman: 'XIX' },
  
  // Many additional scattered stars of various sizes
  { x: 45, y: 30, size: 'tiny' },
  { x: 55, y: 35, size: 'small' },
  { x: 60, y: 42, size: 'tiny' },
  { x: 48, y: 48, size: 'medium' },
  { x: 52, y: 58, size: 'tiny' },
  { x: 40, y: 55, size: 'small' },
  { x: 65, y: 55, size: 'tiny' },
  { x: 35, y: 62, size: 'medium' },
  { x: 58, y: 68, size: 'tiny' },
  { x: 42, y: 75, size: 'small' },
  { x: 68, y: 72, size: 'tiny' },
  { x: 32, y: 48, size: 'small' },
  { x: 72, y: 48, size: 'tiny' },
  { x: 38, y: 38, size: 'medium' },
  { x: 62, y: 32, size: 'tiny' },
  { x: 28, y: 58, size: 'small' },
  { x: 78, y: 62, size: 'tiny' },
  { x: 45, y: 82, size: 'small' },
  { x: 55, y: 78, size: 'tiny' },
  { x: 25, y: 72, size: 'medium' },
  { x: 75, y: 78, size: 'tiny' },
  { x: 22, y: 42, size: 'small' },
  { x: 82, y: 42, size: 'tiny' },
  { x: 48, y: 25, size: 'small' },
  { x: 52, y: 85, size: 'tiny' },
  { x: 35, y: 25, size: 'tiny' },
  { x: 65, y: 85, size: 'small' },
  { x: 58, y: 22, size: 'tiny' },
  { x: 42, y: 88, size: 'tiny' },
  { x: 78, y: 32, size: 'small' },
  { x: 22, y: 68, size: 'tiny' },
  { x: 88, y: 52, size: 'tiny' },
  { x: 12, y: 48, size: 'small' },
  { x: 68, y: 38, size: 'tiny' },
  { x: 32, y: 72, size: 'tiny' },
  { x: 75, y: 58, size: 'small' },
  { x: 25, y: 52, size: 'tiny' },
  { x: 55, y: 45, size: 'tiny' },
  { x: 45, y: 65, size: 'tiny' },
  { x: 65, y: 28, size: 'tiny' },
  { x: 35, y: 82, size: 'small' },
  { x: 85, y: 38, size: 'tiny' },
  { x: 15, y: 62, size: 'tiny' },
  { x: 72, y: 65, size: 'small' },
  { x: 28, y: 28, size: 'tiny' },
  { x: 58, y: 52, size: 'tiny' },
  { x: 42, y: 42, size: 'tiny' },
  { x: 78, y: 78, size: 'small' },
  { x: 22, y: 22, size: 'tiny' },
  { x: 88, y: 68, size: 'tiny' },
  { x: 12, y: 32, size: 'tiny' },
  { x: 65, y: 68, size: 'tiny' },
  { x: 35, y: 32, size: 'small' },
  { x: 52, y: 38, size: 'tiny' },
  { x: 48, y: 72, size: 'tiny' },
  { x: 82, y: 58, size: 'tiny' },
  { x: 18, y: 52, size: 'small' },
  { x: 62, y: 78, size: 'tiny' },
  { x: 38, y: 22, size: 'tiny' },
  { x: 75, y: 42, size: 'tiny' },
  { x: 25, y: 68, size: 'tiny' },
  { x: 55, y: 62, size: 'tiny' },
  { x: 45, y: 38, size: 'tiny' },
  { x: 68, y: 52, size: 'tiny' },
  { x: 32, y: 58, size: 'tiny' },
  { x: 85, y: 72, size: 'tiny' },
  { x: 15, y: 28, size: 'tiny' },
  { x: 58, y: 72, size: 'tiny' },
  { x: 42, y: 28, size: 'tiny' },
  { x: 72, y: 38, size: 'tiny' },
  { x: 28, y: 62, size: 'tiny' },
  { x: 52, y: 48, size: 'tiny' },
  { x: 48, y: 58, size: 'tiny' },
]